name: Deploy Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
  
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: node
        run: |
          npm --version
    
      

