name: Deploy Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Preparando Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      
      - name: testando node
        run: |
          npm --version
    
      

