name: Build

on:
  push:
    branches: [ main ]

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: |
        cd jogo-da-forca/
        ls
        npm install
        ls
        npm install -g @angular/cli
        ls
        ng build --prod

    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        PROJECT_PATH : jogo-da-forca
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
