name: Build

on:
  push:
    branches: [ main ]

jobs:
  firebase-deploy:
    
    env:
      PROJECT_PATH: jogo-da-forca

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - name: Buildando a Aplicação
      run: |
        cd ${{ env.PROJECT_PATH }}/
        npm install
        npm install -g @angular/cli
        ng build --prod
        
    - name: Deployando a Aplicação
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        PROJECT_PATH : ${{ env.PROJECT_PATH }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
