name: Deploy Firebase

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@master
    
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci@v1.0
      
      - name: Deploy Application
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd jogo-da-forca/
          ng deploy
          

      

