name: Deploy Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Preparando Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Preparando Firebase
        run: |
          npm install -g firebase-tools
          firebase --token ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Preparando Angular
        run: npm install -g @angular/cli
      
      - name: Buildando Aplicação
        run: |
          cd jogo-da-forca/
          npm install
          ng build --prod
        
      - name: Deployando a aplicação
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
          

      

